# Copyright (c) 2001, Stanford University
# All rights reserved.
#
# See the file LICENSE.txt for information on redistributing this software.

TOP = .

SUBDIRS = util spu_loader packer state_tracker unpacker dlm vmgl_lib feedback array passthrough render error XExtension pack glstub stub-daemon/libvmglstubdaemon stub-daemon

include $(TOP)/cr.mk

